#!/usr/bin/env python

# my modules
from WarHammer.Dice import D
from WarHammer.CareerPath import CareerPath

def GetCareerData(clas, career):
    '''
    @ params: class and career
    @ returns: CareerPath object which contains basic info about the career path
    '''
    all_paths = {"ACADEMICS": {'Apothecary': CareerPath('Apothecary’s Apprentice',
                                                        'Brass 3',
                                                        ('Consume Alcohol',
                                                         'Heal',
                                                         'Language (Classical)',
                                                         'Lore (Chemistry)',
                                                         'Lore (Medicine)',
                                                         'Lore (Plants)',
                                                         'Trade (Apothecary)',
                                                         'Trade (Poisoner)'),
                                                        ('Concoct',
                                                         'Craftsman (Apothecary)',
                                                         'Etiquette (Scholar)',
                                                         'Read/Write)'),
                                                        ('Book (Blank)',
                                                         'Healing Draught',
                                                         'Leather Jerkin',
                                                         'Pestle and Mortar'), 53),
                               'Engineer': CareerPath('Student Engineer',
                                                      'Brass 4',
                                                      ('Consume Alcohol',
                                                       'Cool',
                                                       'Endurance',
                                                       'Language (Classical)',
                                                       'Lore (Engineer)',
                                                       'Perception',
                                                       'Ranged (Blackpowder)',
                                                       'Trade (Engineer)'),
                                                      ('Artistic', 
                                                       'Gunner',
                                                       'Read/Write',
                                                       'Tinker'),
                                                      ('Book (Engineer)',
                                                       'Hammer and Spikes'), 54),
                               'Lawyer': CareerPath('Student Lawyer',
                                                    'Brass 4',
                                                    ('Consume Alcohol',
                                                     'Endurance',
                                                     'Haggle',
                                                     'Language (Classical)',
                                                     'Lore (Law)',
                                                     'Lore (Theology)',
                                                     'Perception',
                                                     'Research'),
                                                    ('Blather',
                                                     'Etiquette (Scholar)',
                                                     'Read/Write',
                                                     'Speedreader'),
                                                    ('Book (Law)',
                                                     'Magnifying Glass'), 55),
                               'Nun': CareerPath('Novitiate',
                                                 'Brass 1',
                                                 ('Art (Calligraphy)',
                                                  'Cool',
                                                  'Endurance',
                                                  'Entertain (Storyteller)',
                                                  'Gossip',
                                                  'Heal',
                                                  'Lore (Theology)',
                                                  'Pray'),
                                                 ('Bless (Any)',
                                                  'Stone Soup',
                                                  'Panhandle',
                                                  'Read/Write'),
                                                 ('Religious Symbol',
                                                  'Robes'), 56),
                               'Physician': CareerPath('Physician`s Apprentice',
                                                       'Brass 4',
                                                       ('Bribery',
                                                        'Cool',
                                                        'Drive',
                                                        'Endurance',
                                                        'Gossip',
                                                        'Heal',
                                                        'Perception',
                                                        'Sleight of Hand'),
                                                       ('Bookish',
                                                        'Field Dressing',
                                                        'Read/Write',
                                                        'Strike to Stun'),
                                                       ('Bandages',
                                                        'Healing Draught'), 57),
                               'Priest': CareerPath('Initiate',
                                                    'Brass 2',
                                                    ('Athletics',
                                                     'Cool',
                                                     'Endurance',
                                                     'Intuition',
                                                     'Lore (Theology)',
                                                     'Perception',
                                                     'Pray',
                                                     'Research'),
                                                    ('Bless (Any)',
                                                     'Holy Visions',
                                                     'Read/Write',
                                                     'Suave'),
                                                    ('Religious Symbol',
                                                     'Robes'), 58),
                               'Scholar': CareerPath('Student',
                                                     'Brass 3',
                                                     ('Consume Alcohol',
                                                      'Entertain (Storytelling)',
                                                      'Gamble',
                                                      'Gossip',
                                                      'Haggle',
                                                      'Language (Classical)',
                                                      'Lore (Any)',
                                                      'Research'),
                                                     ('Carouser',
                                                      'Read/Write',
                                                      'Savvy',
                                                      'Super Numerate'),
                                                     ('Alcohol',
                                                      'Book',
                                                      'Opinions',
                                                      'Writing Kit'), 59),
                               'Wizard': CareerPath('Wizard`s Apprentice',
                                                    'Brass 3',
                                                    ('Channelling (Any Colour)',
                                                     'Dodge',
                                                     'Intuition',
                                                     'Language (Magick)',
                                                     'Lore (Magic)',
                                                     'Melee (Basic)',
                                                     'Melee (Polearm)',
                                                     'Perception'),
                                                    ('Aethyric Attunement',
                                                     'Petty Magic',
                                                     'Read/Write',
                                                     'Second Sight'),
                                                    ('Grimoire',
                                                     'Quarterstaff'), 60) },
                 "BURGHERS":  {'Agitator': CareerPath('Pamphleteer',
                                                      'Brass 1',
                                                      ('Art (Writing)',
                                                       'Bribery',
                                                       'Charm',
                                                       'Consume Alcohol',
                                                       'Gossip',
                                                       'Haggle',
                                                       'Lore (Politics)',
                                                       'Trade (Printing)'),
                                                      ('Blather',
                                                       'Gregarious',
                                                       'Panhandle',
                                                       'Read/Write'),
                                                      ('Writing Kit',
                                                       'Hammer and Nails',
                                                       'Pile of Leaflets'), 61),
                               'Artisan': CareerPath('Apprentice Artisan',
                                                     'Brass 2',
                                                     ('Athletics',
                                                      'Cool',
                                                      'Consume Alcohol',
                                                      'Dodge',
                                                      'Endurance',
                                                      'Evaluate',
                                                      'Stealth (Urban)',
                                                      'Trade (Any)'),
                                                     ('Artistic',
                                                      'Craftsman (any)',
                                                      'Strong Back',
                                                      'Very Strong'),
                                                     ('Chalk',
                                                      'Leather Jerkin',
                                                      str(D(10))+' rags'), 62),
                               'Beggar': CareerPath('Pauper',
                                                    'Brass 0',
                                                    ('Athletics',
                                                     'Charm',
                                                     'Consume Alcohol',
                                                     'Cool',
                                                     'Dodge',
                                                     'Endurance',
                                                     'Intuition',
                                                     'Stealth (Urban)'),
                                                    ('Panhandle',
                                                     'Resistance (Disease)',
                                                     'Stone Soup',
                                                     'Very Resilient'),
                                                    ('Poor Quality Blanket',
                                                     'Cup'), 63),
                               'Investigator': CareerPath('Sleuth',
                                                          'Silver 1',
                                                          ('Charm',
                                                           'Climb',
                                                           'Cool',
                                                           'Gossip',
                                                           'Intuition',
                                                           'Perception',
                                                           'Stealth (Urban)',
                                                           'Track'),
                                                          ('Alley Cat',
                                                           'Beneath Notice',
                                                           'Read/Write',
                                                           'Sharp'),
                                                          ('Lantern',
                                                           'Lamp Oil',
                                                           'Journal',
                                                           'Quill and Ink'), 64),
                               'Merchant': CareerPath('Trader',
                                                      'Silver 2',
                                                      ('Animal Care',
                                                       'Bribery',
                                                       'Charm',
                                                       'Consume Alcohol',
                                                       'Drive',
                                                       'Gamble',
                                                       'Gossip',
                                                       'Haggle'),
                                                      ('Blather',
                                                       'Dealmaker',
                                                       'Read/Write',
                                                       'Suave'),
                                                      ('Abacus',
                                                       'Mule and Cart',
                                                       'Canvas Tarpaulin',
                                                       str(sum([D(10) for i in range(0, 3)]))+' Silver Shillings'), 65),
                               'Rat Catcher': CareerPath('Rat Hunter',
                                                         'Brass 3',
                                                         ('Athletics',
                                                          'Animal Training (Dog)',
                                                          'Charm Animal',
                                                          'Consume Alcohol',
                                                          'Endurance',
                                                          'Melee (Basic)',
                                                          'Ranged (Sling)',
                                                          'Stealth (Underground or Urban)'),
                                                         ('Night Vision',
                                                          'Resistance (Disease)',
                                                          'Strike Mighty Blow',
                                                          'Strike to Stun'),
                                                         ('Sling with Ammunition',
                                                          'Sack',
                                                          'Small but Vicious Dog'), 66),
                               'Townsman': CareerPath('Clerk',
                                                      'Silver 1',
                                                      ('Charm',
                                                       'Climb',
                                                       'Consume Alcohol',
                                                       'Drive',
                                                       'Dodge',
                                                       'Gamble',
                                                       'Gossip',
                                                       'Haggle'),
                                                      ('Alley Cat',
                                                       'Beneath Notice',
                                                       'Etiquette (Servants)',
                                                       'Sturdy'),
                                                      ('Lodgings',
                                                       'Sturdy Boots'), 67),
                               'Watchman': CareerPath('Watch Recruit',
                                                      'Brass 3',
                                                      ('Athletics',
                                                       'Climb',
                                                       'Consume Alcohol',
                                                       'Dodge',
                                                       'Endurance',
                                                       'Gamble',
                                                       'Melee (Any)',
                                                       'Perception'),
                                                      ('Drilled',
                                                       'Hardy',
                                                       'Strike to Stun',
                                                       'Tenacious'),
                                                      ('Hand Weapon',
                                                       'Leather Jack',
                                                       'Uniform'), 68)},
                 "COURTIERS": {'Advisor': CareerPath('Aide',
                                                     'Silver 2',
                                                     ('Bribery',
                                                      'Consume Alcohol',
                                                      'Endurance',
                                                      'Gossip',
                                                      'Haggle',
                                                      'Language (Classical)',
                                                      'Lore (Politics)',
                                                      'Perception'),
                                                     ('Beneath Notice', 
                                                      'Etiquette (Any)',
                                                      'Gregarious',
                                                      'Read/Write'),
                                                     ('Writing Kit',), 69),
                               'Artist': CareerPath('Apprentice Artist',
                                                    'Silver 1',
                                                    ('Art (Any)',
                                                     'Cool',
                                                     'Consume Alcohol',
                                                     'Evaluate',
                                                     'Endurance',
                                                     'Gossip',
                                                     'Perception',
                                                     'Stealth (Urban)'),
                                                    ('Artistic',
                                                     'Sharp',
                                                     'Strong Back',
                                                     'Tenacious'),
                                                    ('Brush or Chisel or Quill Pen',), 70),
                               'Duellist': CareerPath('Fencer',
                                                      'Silver 3',
                                                      ('Athletics',
                                                       'Dodge',
                                                       'Endurance',
                                                       'Heal',
                                                       'Intuition',
                                                       'Language (Classical)',
                                                       'Melee (Any)',
                                                       'Perception'),
                                                      ('Beat Blade',
                                                       'Distract',
                                                       'Feint',
                                                       'Step Aside'),
                                                      ('Rapier',
                                                       'Sling Bag containing Clothing', 
                                                       str(D(10))+' Bandages'), 71),
                               'Envoy': CareerPath('Herald',
                                                   'Silver 2',
                                                   ('Athletics',
                                                    'Charm',
                                                    'Drive',
                                                    'Dodge',
                                                    'Endurance',
                                                    'Intuition',
                                                    'Ride (Horse)',
                                                    'Row'),
                                                   ('Blather',
                                                    'Etiquette (Nobles)',
                                                    'Read/Write',
                                                    'Suave'),
                                                   ('Leather Jack',
                                                    'Livery',
                                                    'Scroll Case'), 72),
                               'Noble': CareerPath('Scion',
                                                   'Gold 1',
                                                   ('Bribery',
                                                    'Consume Alcohol',
                                                    'Gamble',
                                                    'Intimidate',
                                                    'Leadership',
                                                    'Lore (Heraldry)',
                                                    'Melee (Fencing)',
                                                    'Play (Any)'),
                                                   ('Etiquette (Nobles)',
                                                    'Luck',
                                                    'Noble Blood',
                                                    'Read/Write'),
                                                   ('Courtly Garb',
                                                    'Foil or Hand Mirror',
                                                    'Jewellery worth '+ str(sum([D(10) for i in range(0, 3)])) +' gc',
                                                    'Personal Servant'), 73 ),
                               'Servant': CareerPath('Menial',
                                                     'Silver 1',
                                                     ('Athletics',
                                                      'Climb',
                                                      'Drive',
                                                      'Dodge',
                                                      'Endurance',
                                                      'Intuition',
                                                      'Perception',
                                                      'Stealth (Any)'),
                                                     ('Beneath Notice',
                                                      'Strong Back',
                                                      'Strong-minded',
                                                      'Sturdy'),
                                                     ('Floor Brush', ), 74),
                               'Spy': CareerPath('Informer',
                                                 'Brass 3',
                                                 ('Bribery',
                                                  'Charm',
                                                  'Cool',
                                                  'Gamble',
                                                  'Gossip',
                                                  'Haggle',
                                                  'Perception',
                                                  'Stealth (Any)'),
                                                 ('Blather',
                                                  'Carouser',
                                                  'Gregarious',
                                                  'Shadow'),
                                                 ('Charcoal stick',
                                                  'Sling Bag containing 2 different sets of clothing',
                                                  'Hooded Cloak'), 75),
                               'Warden': CareerPath('Custodian',
                                                    'Silver 1',
                                                    ('Athletics',
                                                     'Charm Animal',
                                                     'Consume Alcohol',
                                                     'Cool',
                                                     'Endurance',
                                                     'Intuition',
                                                     'Lore (Local)',
                                                     'Perception'),
                                                    ('Menacing',
                                                     'Night Vision',
                                                     'Sharp',
                                                     'Strike to Stun'),
                                                    ('Keys',
                                                     'Lantern',
                                                     'Lamp Oil',
                                                     'Livery'), 76)},
                 "PEASANTS":  {'Bailiff': CareerPath('Tax Collector',
                                                     'Silver 1',
                                                     ('Cool',
                                                      'Dodge',
                                                      'Endurance',
                                                      'Gossip',
                                                      'Haggle',
                                                      'Intimidate',
                                                      'Melee (Basic)',
                                                      'Perception'),
                                                     ('Embezzle',
                                                      'Numismatics',
                                                      'Strong Back',
                                                      'Tenacious'),
                                                     ('Hand Weapon',
                                                      'small lock box'), 77),
                               'Hedge Witch': CareerPath('Hedge Apprentice',
                                                         'Brass 1',
                                                         ('Channelling',
                                                          'Endurance',
                                                          'Intuition',
                                                          'Language (Magick)',
                                                          'Lore (Folklore)',
                                                          'Lore (Herbs)',
                                                          'Outdoor Survival',
                                                          'Perception'),
                                                         ('Fast Hands',
                                                          'Petty Magic',
                                                          'Rover',
                                                          'Strider (Woodlands)'),
                                                         (str(D(10))+' Lucky Charms',
                                                          'Quarterstaff',
                                                          'Backpack'), 78),
                               'Herbalist': CareerPath('Herb Gatherer',
                                                       'Brass 2',
                                                       ('Charm Animal',
                                                        'Climb',
                                                        'Endurance',
                                                        'Lore (Herbs)',
                                                        'Outdoor Survival',
                                                        'Perception',
                                                        'Swim',
                                                        'Trade (Herbalist)'),
                                                       ('Acute Sense (Taste)',
                                                        'Orientation',
                                                        'Rover',
                                                        'Strider (any)'),
                                                       ('Boots',
                                                        'Cloak',
                                                        'Sling Bag containing Assortment of Herbs'), 79),
                               'Hunter': CareerPath('Trapper',
                                                    'Brass 2',
                                                    ('Charm Animal',
                                                     'Climb',
                                                     'Endurance',
                                                     'Lore (Beasts)',
                                                     'Outdoor Survival',
                                                     'Perception',
                                                     'Ranged (Sling)',
                                                     'Set Trap'),
                                                    ('Hardy',
                                                     'Rover',
                                                     'Strider (any)',
                                                     'Trapper'),
                                                    ('Selection of Animal Traps',
                                                     'Hand Weapon',
                                                     'Sling with 10 Stone Bullets',
                                                     'Sturdy Boots and Cloak'), 80),
                               'Miner': CareerPath('Prospector',
                                                   'Brass 2',
                                                   ('Cool',
                                                    'Endurance',
                                                    'Intuition',
                                                    'Lore (Local)',
                                                    'Melee (Two-handed)',
                                                    'Outdoor Survival',
                                                    'Perception',
                                                    'Swim'),
                                                   ('Rover',
                                                    'Strider (Rocky)',
                                                    'Sturdy',
                                                    'Tenacious'),
                                                   ('Charcoal Stick',
                                                    'Crude Map',
                                                    'Pan',
                                                    'Spade'), 81),
                               'Mystic': CareerPath('Fortune Teller',
                                                    'Brass 1',
                                                    ('Charm',
                                                     'Entertain (Fortune Telling)',
                                                     'Dodge',
                                                     'Gossip',
                                                     'Haggle',
                                                     'Intuition',
                                                     'Perception',
                                                     'Sleight of Hand'),
                                                    ('Attractive',
                                                     'Luck',
                                                     'Second Sight',
                                                     'Suave'),
                                                    ('Deck of Cards or Dice',
                                                     'Cheap Jewellery'), 82),
                               'Scout': CareerPath('Guide',
                                                   'Brass 3',
                                                   ('Charm Animal',
                                                    'Climb',
                                                    'Endurance',
                                                    'Gossip',
                                                    'Lore (Local)',
                                                    'Melee (Basic)',
                                                    'Outdoor Survival',
                                                    'Perception'),
                                                   ('Orientation',
                                                    'Rover',
                                                    'Sharp',
                                                    'Strider (any)'),
                                                   ('Hand Weapon',
                                                    'Leather Jack',
                                                    'Sturdy Boots and Cloak',
                                                    'Rope'), 83),
                               'Villager': CareerPath('Peasant',
                                                      'Brass 2',
                                                      ('Animal Care',
                                                       'Athletics',
                                                       'Consume Alcohol',
                                                       'Endurance',
                                                       'Gossip',
                                                       'Melee (Brawling)',
                                                       'Lore (Local)',
                                                       'Outdoor Survival'),
                                                      ('Rover',
                                                       'Strong Back',
                                                       'Strong-minded',
                                                       'Stone Soup'),
                                                      (), 84)},
                 "RANGERS":   {'Bounty Hunter': CareerPath('Thief-taker',
                                                           'Silver 1',
                                                           ('Bribery',
                                                            'Charm',
                                                            'Gossip',
                                                            'Haggle',
                                                            'Intuition',
                                                            'Melee (Basic)',
                                                            'Outdoor Survival',
                                                            'Perception'),
                                                           ('Break and Enter',
                                                            'Shadow',
                                                            'Strike to Stun',
                                                            'Suave'),
                                                           ('Hand Weapon',
                                                            'Leather Jerkin',
                                                            'Rope'), 85),
                               'Coachman': CareerPath('Postilion',
                                                      'Silver 1',
                                                      ('Animal Care',
                                                       'Charm Animal',
                                                       'Climb',
                                                       'Drive',
                                                       'Endurance',
                                                       'Perception',
                                                       'Ranged (Entangling)',
                                                       'Ride (Horse)'),
                                                      ('Animal Affinity',
                                                       'Seasoned Traveller',
                                                       'Trick-Riding',
                                                       'Tenacious'),
                                                      ('Warm Coat and Gloves',
                                                       'Whip'), 86),
                               'Entertainer': CareerPath('Busker',
                                                         'Brass 3',
                                                        ('Athletics',
                                                         'Charm',
                                                         'Entertain (Any)',
                                                         'Gossip',
                                                         'Haggle',
                                                         'Perform (Any)',
                                                         'Play (any)',
                                                         'Sleight of Hand'),
                                                         ('Attractive',
                                                          'Mimic',
                                                          'Public-Speaking',
                                                          'Suave'),
                                                         ('Bowl',
                                                          'Instrument'), 87),
                               'Flagellant': CareerPath('Zealot',
                                                        'Brass 0',
                                                        ('Dodge',
                                                         'Endurance',
                                                         'Heal',
                                                         'Intimidate',
                                                         'Intuition',
                                                         'Lore (Sigmar)',
                                                         'Melee (Flail)',
                                                         'Outdoor Survival'),
                                                        ('Berserk Charge',
                                                         'Frenzy',
                                                         'Read/Write',
                                                         'Stone Soup'),
                                                        ('Flail',
                                                         'Tattered Robes'), 88),
                               'Messenger': CareerPath('Runner',
                                                       'Brass 3',
                                                       ('Athletics',
                                                        'Climb',
                                                        'Dodge',
                                                        'Endurance',
                                                        'Gossip',
                                                        'Navigation',
                                                        'Perception',
                                                        'Melee (Brawling)'),
                                                       ('Flee!',
                                                        'Fleet Footed',
                                                        'Sprinter',
                                                        'Step Aside'),
                                                       ('Scroll Case',), 89),
                               'Pedlar': CareerPath('Vagabond',
                                                    'Brass 1',
                                                    ('Charm',
                                                     'Endurance',
                                                     'Entertain (Storytelling)',
                                                     'Gossip',
                                                     'Haggle',
                                                     'Intuition',
                                                     'Outdoor Survival',
                                                     'Stealth (Rural or Urban)'),
                                                    ('Fisherman',
                                                     'Flee!',
                                                     'Rover',
                                                     'Tinker'),
                                                    ('Backpack',
                                                     'Bedroll',
                                                     'Goods worth '+str(sum([D(10) for i in range(0, 3)]))+' Brass',
                                                     'Tent'), 90),
                               'Road Warden': CareerPath('Toll Keeper',
                                                         'Brass 5',
                                                         ('Bribery',
                                                          'Consume Alcohol',
                                                          'Gamble',
                                                          'Gossip',
                                                          'Haggle',
                                                          'Melee (Basic)',
                                                          'Perception',
                                                          'Ranged (Crossbow)'),
                                                         ('Coolheaded',
                                                          'Embezzle',
                                                          'Marksman',
                                                          'Numismatics'),
                                                         ('Crossbow with 10 Bolts',
                                                          'Leather Jack'), 91),
                               'Witch Hunter': CareerPath('Interrogator',
                                                          'Silver 1',
                                                          ('Charm',
                                                           'Consume Alcohol',
                                                           'Heal',
                                                           'Intimidate',
                                                           'Intuition',
                                                           'Lore (Torture)',
                                                           'Melee (Brawling)',
                                                           'Perception'),
                                                          ('Coolheaded',
                                                           'Menacing',
                                                           'Read/Write',
                                                           'Resolute'),
                                                          ('Hand Weapon',
                                                           'Instruments of Torture'), 92)},
                 "RIVERFOLK": {'Boatman': CareerPath('Boat-hand',
                                                     'Silver 1',
                                                     ('Consume Alcohol',
                                                      'Dodge',
                                                      'Endurance',
                                                      'Gossip',
                                                      'Melee (Brawling)',
                                                      'Row',
                                                      'Sail',
                                                      'Swim'),
                                                     ('Dirty Fighting',
                                                      'Fisherman',
                                                      'Strong Back',
                                                      'Strong',
                                                      'Swimmer'),
                                                     ('Hand Weapon (Boat Hook)',
                                                      'Leather Jack',
                                                      'Pole'), 93),
                               'Huffer': CareerPath('Riverguide',
                                                    'Brass 4',
                                                    ('Consume Alcohol',
                                                     'Gossip',
                                                     'Intuition',
                                                     'Lore (Local)',
                                                     'Lore (Riverways)',
                                                     'Perception',
                                                     'Row',
                                                     'Swim'),
                                                    ('Fisherman',
                                                     'Night Vision', 
                                                     'Orientation',
                                                     'Waterman'),
                                                    ('Hand Weapon (Boat Hook)',
                                                     'Storm Lantern and Oil)'), 94),
                               'Riverwarden': CareerPath('River Recruit',
                                                         'Silver 1',
                                                         ('Athletics',
                                                          'Dodge',
                                                          'Endurance',
                                                          'Melee (Basic)',
                                                          'Perception',
                                                          'Row',
                                                          'Sail',
                                                          'Swim'),
                                                         ('Strong Swimmer',
                                                          'Strong Back',
                                                          'Very Strong',
                                                          'Waterman'),
                                                         ('Hand Weapon (Sword)',
                                                          'Leather Jack',
                                                          'Uniform'), 95), 
                               'Riverwoman': CareerPath('Greenfish',
                                                        'Brass 2',
                                                        ('Athletics',
                                                         'Consume Alcohol',
                                                         'Dodge',
                                                         'Endurance',
                                                         'Gossip',
                                                         'Outdoor Survival',
                                                         'Row',
                                                         'Swim'),
                                                        ('Fisherman',
                                                         'Gregarious',
                                                         'Strider (Marshes)',
                                                         'Strong Swimmer'),
                                                        ('Bucket',
                                                         'Fishing Rod and Bait',
                                                         'Leather Leggings'), 96),
                               'Seaman': CareerPath('Landsman',
                                                    'Silver 1',
                                                    ('Climb',
                                                     'Consume Alcohol',
                                                     'Gamble',
                                                     'Gossip',
                                                     'Row',
                                                     'Melee (Brawling)',
                                                     'Sail',
                                                     'Swim'),
                                                    ('Fisherman',
                                                     'Strider (Coastal)',
                                                     'Strong Back',
                                                     'Strong Swimmer'),
                                                    ('Bucket',
                                                     'Brush',
                                                     'Mop'), 97),
                               'Smuggler': CareerPath('River Runner',
                                                      'Brass 2',
                                                      ('Athletics',
                                                       'Bribery',
                                                       'Cool',
                                                       'Consume Alcohol',
                                                       'Row',
                                                       'Sail',
                                                       'Stealth (Rural or Urban)',
                                                       'Swim'),
                                                      ('Criminal',
                                                       'Fisherman',
                                                       'Strider (Marshes)',
                                                       'Strong Back'),
                                                      ('Large Sack',
                                                       'Mask or Scarves',
                                                       'Tinderbox',
                                                       'Storm Lantern and Oil'), 98),
                               'Stevedore': CareerPath('Dockhand',
                                                       'Brass 3',
                                                       ('Athletics',
                                                        'Climb',
                                                        'Consume Alcohol',
                                                        'Dodge',
                                                        'Endurance',
                                                        'Gossip',
                                                        'Melee (Basic)',
                                                        'Swim'),
                                                       ('Dirty Fighting',
                                                        'Strong Back',
                                                        'Sturdy',
                                                        'Very Strong'),
                                                       ('Hand Weapon (Boat Hook)',
                                                        'Leather Gloves'), 99),
                               'Wrecker': CareerPath('Cargo Scavenger',
                                                     'Brass 2',
                                                     ('Climb',
                                                      'Consume Alcohol',
                                                      'Dodge',
                                                      'Endurance',
                                                      'Row',
                                                      'Melee (Basic)',
                                                      'Outdoor Survival',
                                                      'Swim'),
                                                     ('Break and Enter',
                                                      'Criminal',
                                                      'Fisherman',
                                                      'Strong Back'),
                                                     ('Crowbar',
                                                      'Large Sack',
                                                      'Leather Gloves'), 100)},
                 "ROGUES":    {'Bawd': CareerPath('Hustler',
                                                  'Brass 1',
                                                  ('Bribery',
                                                   'Charm',
                                                   'Consume Alcohol',
                                                   'Entertain (Any)',
                                                   'Gamble',
                                                   'Gossip',
                                                   'Haggle',
                                                   'Intimidate'),
                                                  ('Attractive',
                                                   'Alley Cat',
                                                   'Blather',
                                                   'Gregarious'),
                                                  ('Flask of Spirits', ), 101), 
                               'Charlatan': CareerPath('Swindler',
                                                       'Brass 3',
                                                       ('Bribery',
                                                        'Consume Alcohol',
                                                        'Charm',
                                                        'Entertain (Storytelling)',
                                                        'Gamble',
                                                        'Gossip',
                                                        'Haggle',
                                                        'Sleight of Hand'),
                                                       ('Cardsharp',
                                                        'Diceman',
                                                        'Etiquette (Any)',
                                                        'Luck'),
                                                       ('Backpack',
                                                        '2 Sets of Clothing',
                                                        'Deck of Cards',
                                                        'Dice'), 102),
                               'Fence': CareerPath('Broker',
                                                   'Silver 1',
                                                   ('Charm',
                                                    'Consume Alcohol',
                                                    'Dodge',
                                                    'Evaluate',
                                                    'Gamble',
                                                    'Gossip',
                                                    'Haggle',
                                                    'Melee (Basic)'),
                                                   ('Alley Cat',
                                                    'Cardsharp',
                                                    'Dealmaker',
                                                    'Gregarious'),
                                                   ('Hand Weapon',
                                                    'Stolen Goods worth '+str(sum([D(10) for i in range(0, 3)]))+' Shillings'), 103),
                               'Grave Robber': CareerPath('Body Snatcher',
                                                          'Brass 2',
                                                          ('Climb',
                                                           'Cool',
                                                           'Dodge',
                                                           'Endurance',
                                                           'Gossip',
                                                           'Intuition',
                                                           'Perception',
                                                           'Stealth (Any)'),
                                                          ('Alley Cat',
                                                           'Criminal',
                                                           'Flee!',
                                                           'Strong Back'),
                                                          ('Crowbar',
                                                           'Handcart',
                                                           'Hooded Cloak',
                                                           'Tarpaulin'), 104),
                               'Outlaw': CareerPath('Brigand',
                                                    'Brass 1',
                                                    ('Athletics',
                                                     'Consume Alcohol',
                                                     'Cool',
                                                     'Endurance',
                                                     'Gamble',
                                                     'Intimidate',
                                                     'Melee (Basic)',
                                                     'Outdoor Survival'),
                                                    ('Combat Aware',
                                                     'Criminal',
                                                     'Rover',
                                                     'Flee!'),
                                                    ('Bedroll',
                                                     'Hand Weapon',
                                                     'Leather Jerkin',
                                                     'Tinderbox'), 105),
                               'Racketeer': CareerPath('Thug',
                                                       'Brass 3',
                                                       ('Consume Alcohol',
                                                        'Cool',
                                                        'Dodge',
                                                        'Endurance',
                                                        'Intimidate',
                                                        'Lore (Local)',
                                                        'Melee (Brawling)',
                                                        'Stealth (Urban)'),
                                                       ('Criminal',
                                                        'Etiquette (Criminals)',
                                                        'Menacing',
                                                        'Strike Mighty Blow'),
                                                       ('Knuckledusters',
                                                        'Leather Jack'), 106),
                               'Thief': CareerPath('Prowler',
                                                   'Brass 1',
                                                   ('Athletics',
                                                    'Climb',
                                                    'Cool',
                                                    'Dodge',
                                                    'Endurance',
                                                    'Intuition',
                                                    'Perception',
                                                    'Stealth (Urban)'),
                                                   ('Alley Cat',
                                                    'Criminal',
                                                    'Flee!',
                                                    'Strike to Stun'),
                                                   ('Crowbar',
                                                    'Leather Jerkin',
                                                    'Sack'), 107),
                               'Witch': CareerPath('Hexer',
                                                   'Brass 1',
                                                   ('Channelling',
                                                    'Cool',
                                                    'Endurance',
                                                    'Gossip',
                                                    'Intimidate',
                                                    'Language (Magick)',
                                                    'Sleight of Hand',
                                                    'Stealth (Rural)'),
                                                   ('Criminal',
                                                    'Instinctive Diction',
                                                    'Menacing',
                                                    'Petty Magic'),
                                                   ('Candles',
                                                    'Chalk',
                                                    'Doll',
                                                    'Pins'), 108)},
                 "WARRIORS":    {'Cavalryman': CareerPath('Horseman',
                                                          'Silver 2',
                                                         ('Animal Care',
                                                          'Charm Animal',
                                                          'Endurance',
                                                          'Language (Battle)',
                                                          'Melee (Basic)',
                                                          'Outdoor Survival',
                                                          'Perception',
                                                          'Ride (Horse)'),
                                                         ('Combat Aware',
                                                          'Crack the Whip',
                                                          'Lightning Reflexes',
                                                          'Roughrider'),
                                                         ('Leather Jack',
                                                          'Riding Horse with Saddle and Tack'), 109),
                                 'Guard': CareerPath('Sentry',
                                                     'Silver 1',
                                                     ('Consume Alcohol',
                                                      'Endurance',
                                                      'Entertain (Storytelling)',
                                                      'Gamble',
                                                      'Gossip',
                                                      'Intuition',
                                                      'Melee (Basic)',
                                                      'Perception'),
                                                     ('Diceman',
                                                      'Etiquette (Servants)',
                                                      'Strike to Stun',
                                                      'Tenacious'),
                                                     ('Buckler',
                                                      'Leather Jerkin',
                                                      'Storm Lantern with Oil'), 110),
                                'Knight': CareerPath('Squire',
                                                     'Silver 3',
                                                     ('Athletics',
                                                      'Animal Care',
                                                      'Charm Animal',
                                                      'Heal',
                                                      'Lore (Heraldry)',
                                                      'Melee (Cavalry)',
                                                      'Ride (Horse)',
                                                      'Trade (Farrier)'),
                                                     ('Etiquette (any)',
                                                      'Roughrider',
                                                      'Sturdy',
                                                      'Warrior Born'),
                                                     ('Leather Jack',
                                                      'Mail Shirt',
                                                      'Riding Horse with Saddle and Tack',
                                                      'Shield',
                                                      'Trade Tools (Farrier)'), 111),
                                 'Pit Fighter': CareerPath('Pugilist',
                                                           'Brass 4',
                                                           ('Athletics',
                                                            'Cool',
                                                            'Dodge',
                                                            'Endurance',
                                                            'Gamble',
                                                            'Intimidate',
                                                            'Melee (Any)',
                                                            'Melee (Brawling)'),
                                                           ('Dirty Fighting',
                                                            'In-fighter',
                                                            'Iron Jaw',
                                                            'Reversal'),
                                                           ('Bandages',
                                                            'Knuckledusters',
                                                            'Leather Jack'), 112),
                                 'Protagonist': CareerPath('Braggart',
                                                           'Brass 2',
                                                           ('Athletics',
                                                            'Dodge',
                                                            'Endurance',
                                                            'Entertain (Taunt)',
                                                            'Gossip',
                                                            'Haggle',
                                                            'Intimidate',
                                                            'Melee (Any)'),
                                                           ('In-fighter',
                                                            'Dirty Fighting',
                                                            'Menacing',
                                                            'Warrior Born'),
                                                           ('Hood or Mask',
                                                            'Knuckledusters',
                                                            'Leather Jack'), 113),
                                 'Slayer': CareerPath('Troll Slayer',
                                                      'Brass 2',
                                                      ('Consume Alcohol',
                                                       'Cool',
                                                       'Dodge,'
                                                       'Endurance',
                                                       'Gamble',
                                                       'Heal',
                                                       'Lore (Trolls)',
                                                       'Melee (Basic)'),
                                                      ('Dual Wielder',
                                                       'Fearless (Everything)',
                                                       'Frenzy',
                                                       'Slayer'),
                                                      ('Axe',
                                                       'Flask of Spirits',
                                                       'Shame',
                                                       'Tattoos'), 114),
                                 'Soldier': CareerPath('Recruit',
                                                       'Silver 1',
                                                       ('Athletics',
                                                        'Climb',
                                                        'Cool',
                                                        'Dodge',
                                                        'Endurance',
                                                        'Language (Battle)',
                                                        'Melee (Basic)',
                                                        'Play (Drum or Fife)'),
                                                       ('Diceman',
                                                        'Marksman',
                                                        'Strong Back',
                                                        'Warrior Born'),
                                                       ('Dagger',
                                                        'Leather Breastplate',
                                                        'Uniform'), 115),
                                 'Warrior Priest': CareerPath('Novitiate',
                                                              'Brass 2',
                                                              ('Cool',
                                                               'Dodge',
                                                               'Endurance',
                                                               'Heal',
                                                               'Leadership',
                                                               'Lore (Theology)',
                                                               'Melee (Any)',
                                                               'Pray'),
                                                              ('Bless (Any)',
                                                               'Etiquette (Cultists)',
                                                               'Read/Write',
                                                               'Strong-minded'),
                                                              ('Book (Religion)',
                                                               'Leather Jerkin',
                                                               'Religious Symbol',
                                                               'Robes',
                                                               'Weapon (Any Melee)'), 116)}}
    
    
    
    return all_paths[clas][career]


                                                
